/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Aitrans: typeof import('./src/components/aitrans.vue')['default']
    AsideFrame: typeof import('./src/components/asideFrame.vue')['default']
    BookCatalog: typeof import('./src/components/collapse/bookCatalog.vue')['default']
    BookViewer: typeof import('./src/components/bookViewer.vue')['default']
    ChatHis: typeof import('./src/components/collapse/chatHis.vue')['default']
    Collapse: typeof import('./src/components/collapse.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSplitter: typeof import('element-plus/es')['ElSplitter']
    ElSplitterPanel: typeof import('element-plus/es')['ElSplitterPanel']
    ElTree: typeof import('element-plus/es')['ElTree']
    MainIntfc: typeof import('./src/components/mainIntfc.vue')['default']
    QueryFrame: typeof import('./src/components/queryFrame.vue')['default']
    Reader: typeof import('./src/components/reader.vue')['default']
    ReaderSet: typeof import('./src/components/collapse/readerSet.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
