/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Aside: typeof import('./src/components/aside.vue')['default']
    AsideFrame: typeof import('./src/components/asideFrame.vue')['default']
    Book: typeof import('./src/components/book.vue')['default']
    BookFrame: typeof import('./src/components/collapse/bookFrame.vue')['default']
    BookViewer: typeof import('./src/components/bookViewer.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSplitter: typeof import('element-plus/es')['ElSplitter']
    ElSplitterPanel: typeof import('element-plus/es')['ElSplitterPanel']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    MainInterface: typeof import('./src/components/mainInterface.vue')['default']
    MainIntfc: typeof import('./src/components/mainIntfc.vue')['default']
    Reader: typeof import('./src/components/reader.vue')['default']
  }
}
